/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface-container": "#1d2021",
        "on-tertiary": "#2f3131",
        "error-container": "#93000a",
        "on-primary-fixed": "#390c00",
        "error": "#ffb4ab",
        "outline-variant": "#594139",
        "surface-tint": "#ffb59d",
        "on-primary": "#5d1900",
        "tertiary-container": "#999a9a",
        "secondary": "#eec140",
        "background": "#111415",
        "on-background": "#e1e3e4",
        "secondary-fixed-dim": "#eec140",
        "on-tertiary-fixed": "#1a1c1c",
        "primary": "#ffb59d",
        "on-error-container": "#ffdad6",
        "inverse-primary": "#ab3500",
        "surface-dim": "#111415",
        "surface-variant": "#323536",
        "on-secondary-fixed-variant": "#594400",
        "surface-container-highest": "#323536",
        "on-surface": "#e1e3e4",
        "on-secondary-container": "#382a00",
        "secondary-container": "#b68e01",
        "on-secondary": "#3e2e00",
        "inverse-on-surface": "#2e3132",
        "inverse-surface": "#e1e3e4",
        "primary-fixed": "#ffdbd0",
        "on-primary-fixed-variant": "#832600",
        "on-primary-container": "#5f1900",
        "surface-container-lowest": "#0c0f10",
        "on-tertiary-container": "#303232",
        "outline": "#a98a80",
        "primary-fixed-dim": "#ffb59d",
        "surface-container-high": "#272a2b",
        "surface-container-low": "#191c1d",
        "surface": "#111415",
        "surface-bright": "#373a3b",
        "tertiary": "#c6c6c7",
        "secondary-fixed": "#ffdf92",
        "on-surface-variant": "#e1bfb5",
        "on-secondary-fixed": "#241a00",
        "tertiary-fixed": "#e2e2e2",
        "on-error": "#690005",
        "tertiary-fixed-dim": "#c6c6c7",
        "on-tertiary-fixed-variant": "#454747",
        "primary-container": "#ff6b35"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "stack-md": "24px",
        "gutter": "16px",
        "container-padding": "24px",
        "base": "8px",
        "stack-sm": "12px",
        "stack-lg": "48px"
      },
      fontFamily: {
        "headline-lg": ["Plus Jakarta Sans", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "headline-lg-mobile": ["Plus Jakarta Sans", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "label-sm": ["Inter", "sans-serif"],
        "headline-md": ["Plus Jakarta Sans", "sans-serif"],
        "display-lg": ["Plus Jakarta Sans", "sans-serif"],
        "label-md": ["Inter", "sans-serif"]
      },
      fontSize: {
        "headline-lg": ["32px", {"lineHeight": "1.2", "fontWeight": "700"}],
        "body-md": ["16px", {"lineHeight": "1.6", "fontWeight": "400"}],
        "headline-lg-mobile": ["24px", {"lineHeight": "1.2", "fontWeight": "700"}],
        "body-lg": ["18px", {"lineHeight": "1.6", "fontWeight": "400"}],
        "label-sm": ["12px", {"lineHeight": "1.2", "fontWeight": "500"}],
        "headline-md": ["24px", {"lineHeight": "1.3", "fontWeight": "600"}],
        "display-lg": ["48px", {"lineHeight": "1.1", "letterSpacing": "-0.02em", "fontWeight": "800"}],
        "label-md": ["14px", {"lineHeight": "1.2", "letterSpacing": "0.05em", "fontWeight": "600"}]
      },
      backgroundImage: {
        'accent-gradient': 'linear-gradient(135deg, #ff6b35 0%, #f7c948 100%)',
        'hero-radial':     'radial-gradient(ellipse at 70% 50%, rgba(255,107,53,0.08) 0%, transparent 65%)',
      }
    },
  },
  plugins: [],
}
